#name: # project name.
#accessToken: # github personal access token.
#url: # github web url.
#---
#name: ngrinder # ex1.
#accessToken: e1a47e652762b60a...3ddc0713b07g13k
#url: https://github.com/naver/ngrinder.git
#---
#name: linux # ex2.
#accessToken: t9a47e6ff262b60a...3dac0713b07e82a
#url: https://github.com/torvalds/linux.git
